# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stonowisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pracodawca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='id_firmy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Pracodawca'),
        ),
    ]
