# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isEmployer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pracodawca',
            new_name='Company',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='id_firmy',
        ),
        migrations.DeleteModel(
            name='Uzytkownik',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Company'),
        ),
        migrations.AddField(
            model_name='form',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Offer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Form'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Question'),
        ),
    ]
